# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
    ]
