# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
